### ISSUE TITLE
How to run to get the result of Table 1b in the paper

### ISSUE THREAD

**Issue by zhude233** [AIRLABkhu/A2XP#3]
![image](https://github.com/user-attachments/assets/7f35045e-5fda-408d-8e2e-4350b9277bd6)

**Comment by nda111** [comment]
This table doesn't show the single-domain generalization result. 
As mentioned in Section 4.3, the numbers represent the accuracy on the source domains that are used to train the experts and the attention module.

**Comment by zhude233** [comment]
So the data in Table b1 is the data obtained from training in what fields and testing in what fields? The data given in the table appears to be trained on a single domain and tested on other domains. And I want to know how to run the repository code to get the data for this table

**Comment by zhude233** [comment]
I raise this question because the paper does not seem to introduce in detail the conditions under which Table 1(b) is trained and these data are obtained, such as whether expert is used or not. 
And if expert is used, how to select expert, such as four experts trained in P field by four different initialization methods, and these four experts are then combined to train different domains

**Comment by nda111** [comment]
As the section title says, the data is about evaluating A2XP on the source domains. 
For example, the number in the (target:P, source:A) cell means it used all experts of A, C, and S domains and tested on the A domain. 
What we tried to show by this table is that the ability of experts still remains after the experts are mixed through cross-attention module. 

We initialized the experts with meta initialization and other settings were set as the default described in section 4.1. 

And this repository doesn't explicitly provide the code to obtain this data. 
But you can easily modify the evaluation code of train.py file for that.

**Comment by zhude233** [comment]
Thank you for your answer
